language: scala
scala:
  - 2.9.1
branches:
  only:
    - develop
before_install:
  - git submodule update --init --recursive
  - wget http://dl.google.com/android/android-sdk_r18-linux.tgz
  - tar -zxf android-sdk_r18-linux.tgz
  - export ANDROID_HOME=~/builds/sdb/cloudr/android-sdk-linux
  - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools
  - android update sdk --filter tools,platform-tools --no-ui --force
  - android update sdk --filter android-10,extra-android-support --no-ui --force
  - export SBT_OPTS="-Xms512m -Xmx1024m -XX:MaxPermSize=256m -Xss4m -XX:ReservedCodeCacheSize=64m -XX:+CMSClassUnloadingEnabled"